name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: denoland/setup-deno@main
        with:
          deno-version: "1.10.1"

      - name: Run fmt
        run: deno fmt --check

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: deno test --import-map import_map.json

      - name: Run build
        run: make
