name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: denoland/setup-deno@main
        with:
          deno-version: "1.10.1"

      - name: Run fmt
        run: deno fmt --check

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: make test

      - name: Generate lcov
        run: deno coverage --lcov ./cov > cov.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: cov.lcov

      - name: Run build
        run: make
