name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: denoland/setup-deno@main
        with:
          deno-version: "1.38.2"

      - name: Run fmt
        run: deno fmt --check

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: make test

      - name: Run build
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "bin/ytdl-best*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
